version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/_data # where "db" is the name of previously created volume /home/dev09/postgresql/data
        - - .:/var/lib/postgresql/_data # save data to host
    healthcheck:
      test: ping
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 30s